-- =============================================================================
-- Project Atlas — Step 10A REMOTE-SAFE behavioral checks
-- Target: development remote database ONLY (never production).
--
-- Guarantees:
--   * Single explicit transaction: BEGIN … ROLLBACK
--   * No COMMIT
--   * No DELETE/UPDATE on preexisting rows
--   * All INSERT use gen_random_uuid() seeds + one technical run_marker
--   * Expected failures caught in nested EXCEPTION blocks (txn stays open)
--   * No payload JSON, PII, JWT, passwords, or seed UUIDs in NOTICE/output
--
-- Auth simulation (compatible with auth.uid() / RLS helpers):
--   SET LOCAL ROLE authenticated;
--   set_config('request.jwt.claim.sub', <temp_user>::text, true);
--   set_config('request.jwt.claims', jsonb with sub+role, true);
--
-- Temporary auth.users rows are required because:
--   public.profiles.id → auth.users(id)
--   public.company_members.user_id → public.profiles(id)
--   and the on_auth_user_created trigger creates profiles on insert.
-- They exist only inside this transaction and disappear on ROLLBACK.
--
-- Deduplicazione email: best effort dello Step 10A (non garanzia database).
--
-- run_marker (hyphenated, slug-safe, non-sensitive):
--   step10a-remote-<randomhex>
-- Embedded only in technical company slug/name, example.invalid emails,
-- and technical metadata. Exposed once via test_results.safe_message for
-- row test_name = 'run_marker' so a SECOND connection can count residuals:
--   auth.users / profiles / companies / company_members / clients
-- filtered by that marker — expected counts all 0 after ROLLBACK.
-- =============================================================================

BEGIN;

CREATE TEMP TABLE test_results (
  test_name TEXT NOT NULL,
  passed BOOLEAN NOT NULL,
  error_code TEXT,
  safe_message TEXT
) ON COMMIT DROP;

-- Tracks exclusively UUID generated by this script (never printed).
CREATE TEMP TABLE test_seed (
  kind TEXT NOT NULL,
  id UUID NOT NULL
) ON COMMIT DROP;

DO $body$
DECLARE
  v_run_marker TEXT :=
    'step10a-remote-'
    || substr(replace(gen_random_uuid()::text, '-', ''), 1, 20);
  v_owner UUID := gen_random_uuid();
  v_admin UUID := gen_random_uuid();
  v_manager UUID := gen_random_uuid();
  v_employee UUID := gen_random_uuid();
  v_company_a UUID := gen_random_uuid();
  v_company_b UUID := gen_random_uuid();
  v_slug_a TEXT := v_run_marker || '-a';
  v_slug_b TEXT := v_run_marker || '-b';
  v_inserted BIGINT;
  v_skipped BIGINT;
  v_rows INTEGER[];
  v_count_before BIGINT;
  v_count_after BIGINT;
  v_sqlstate TEXT;
  v_elem JSONB;
  v_ok BOOLEAN;
BEGIN
  INSERT INTO test_results VALUES (
    'run_marker',
    true,
    NULL,
    v_run_marker
  );

  INSERT INTO test_seed (kind, id) VALUES
    ('user', v_owner),
    ('user', v_admin),
    ('user', v_manager),
    ('user', v_employee),
    ('company', v_company_a),
    ('company', v_company_b);

  -- Seed temporary auth users (transaction-local; required for FK + profiles trigger).
  INSERT INTO auth.users (
    id, instance_id, aud, role, email, encrypted_password,
    email_confirmed_at, raw_app_meta_data, raw_user_meta_data,
    created_at, updated_at
  )
  VALUES
    (v_owner, '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated',
     'owner.' || v_run_marker || '@example.invalid',
     crypt('step10a-test-only', gen_salt('bf')), now(),
     '{"provider":"email","providers":["email"]}'::jsonb,
     jsonb_build_object('full_name', v_run_marker || '-owner'), now(), now()),
    (v_admin, '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated',
     'admin.' || v_run_marker || '@example.invalid',
     crypt('step10a-test-only', gen_salt('bf')), now(),
     '{"provider":"email","providers":["email"]}'::jsonb,
     jsonb_build_object('full_name', v_run_marker || '-admin'), now(), now()),
    (v_manager, '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated',
     'manager.' || v_run_marker || '@example.invalid',
     crypt('step10a-test-only', gen_salt('bf')), now(),
     '{"provider":"email","providers":["email"]}'::jsonb,
     jsonb_build_object('full_name', v_run_marker || '-manager'), now(), now()),
    (v_employee, '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated',
     'employee.' || v_run_marker || '@example.invalid',
     crypt('step10a-test-only', gen_salt('bf')), now(),
     '{"provider":"email","providers":["email"]}'::jsonb,
     jsonb_build_object('full_name', v_run_marker || '-employee'), now(), now());

  INSERT INTO public.companies (id, name, slug)
  VALUES
    (v_company_a, v_run_marker || '-company-a', v_slug_a),
    (v_company_b, v_run_marker || '-company-b', v_slug_b);

  INSERT INTO public.company_members (company_id, user_id, role)
  VALUES
    (v_company_a, v_owner, 'owner'),
    (v_company_a, v_admin, 'admin'),
    (v_company_a, v_manager, 'manager'),
    (v_company_a, v_employee, 'employee'),
    (v_company_b, v_owner, 'owner');

  -- Auth context for SECURITY INVOKER + RLS helpers.
  SET LOCAL ROLE authenticated;

  -- ---------- auth helpers ----------
  -- Clears JWT subject so auth.uid() is null.
  -- not_authenticated
  BEGIN
    PERFORM set_config('request.jwt.claim.sub', '', true);
    PERFORM set_config('request.jwt.claims', '{}', true);
    PERFORM public.import_customers(
      v_company_a,
      jsonb_build_array(jsonb_build_object('source_row', 2, 'name', 'step10a-x'))
    );
    INSERT INTO test_results VALUES (
      'not_authenticated', false, NULL, 'expected SQLSTATE 28000'
    );
  EXCEPTION
    WHEN SQLSTATE '28000' THEN
      INSERT INTO test_results VALUES ('not_authenticated', true, '28000', 'rejected');
    WHEN OTHERS THEN
      GET STACKED DIAGNOSTICS v_sqlstate = RETURNED_SQLSTATE;
      INSERT INTO test_results VALUES (
        'not_authenticated', false, v_sqlstate, 'unexpected sqlstate'
      );
  END;

  -- employee_rejected
  BEGIN
    PERFORM set_config('request.jwt.claim.sub', v_employee::text, true);
    PERFORM set_config(
      'request.jwt.claims',
      json_build_object('sub', v_employee::text, 'role', 'authenticated')::text,
      true
    );
    PERFORM public.import_customers(
      v_company_a,
      jsonb_build_array(jsonb_build_object('source_row', 2, 'name', 'step10a-emp'))
    );
    INSERT INTO test_results VALUES (
      'employee_rejected', false, NULL, 'expected SQLSTATE 42501'
    );
  EXCEPTION
    WHEN SQLSTATE '42501' THEN
      INSERT INTO test_results VALUES ('employee_rejected', true, '42501', 'rejected');
    WHEN OTHERS THEN
      GET STACKED DIAGNOSTICS v_sqlstate = RETURNED_SQLSTATE;
      INSERT INTO test_results VALUES (
        'employee_rejected', false, v_sqlstate, 'unexpected sqlstate'
      );
  END;

  -- owner_authorized
  BEGIN
    PERFORM set_config('request.jwt.claim.sub', v_owner::text, true);
    PERFORM set_config(
      'request.jwt.claims',
      json_build_object('sub', v_owner::text, 'role', 'authenticated')::text,
      true
    );
    SELECT inserted_count INTO v_inserted
    FROM public.import_customers(
      v_company_a,
      jsonb_build_array(jsonb_build_object('source_row', 2, 'name', 'step10a-owner-row'))
    );
    INSERT INTO test_results VALUES (
      'owner_authorized',
      v_inserted = 1,
      NULL,
      CASE WHEN v_inserted = 1 THEN 'inserted_ok' ELSE 'unexpected_count' END
    );
  EXCEPTION
    WHEN OTHERS THEN
      GET STACKED DIAGNOSTICS v_sqlstate = RETURNED_SQLSTATE;
      INSERT INTO test_results VALUES (
        'owner_authorized', false, v_sqlstate, 'unexpected sqlstate'
      );
  END;

  -- admin_authorized
  BEGIN
    PERFORM set_config('request.jwt.claim.sub', v_admin::text, true);
    PERFORM set_config(
      'request.jwt.claims',
      json_build_object('sub', v_admin::text, 'role', 'authenticated')::text,
      true
    );
    SELECT inserted_count INTO v_inserted
    FROM public.import_customers(
      v_company_a,
      jsonb_build_array(jsonb_build_object('source_row', 2, 'name', 'step10a-admin-row'))
    );
    INSERT INTO test_results VALUES (
      'admin_authorized',
      v_inserted = 1,
      NULL,
      CASE WHEN v_inserted = 1 THEN 'inserted_ok' ELSE 'unexpected_count' END
    );
  EXCEPTION
    WHEN OTHERS THEN
      GET STACKED DIAGNOSTICS v_sqlstate = RETURNED_SQLSTATE;
      INSERT INTO test_results VALUES (
        'admin_authorized', false, v_sqlstate, 'unexpected sqlstate'
      );
  END;

  -- manager_authorized
  BEGIN
    PERFORM set_config('request.jwt.claim.sub', v_manager::text, true);
    PERFORM set_config(
      'request.jwt.claims',
      json_build_object('sub', v_manager::text, 'role', 'authenticated')::text,
      true
    );
    SELECT inserted_count INTO v_inserted
    FROM public.import_customers(
      v_company_a,
      jsonb_build_array(jsonb_build_object('source_row', 2, 'name', 'step10a-manager-row'))
    );
    INSERT INTO test_results VALUES (
      'manager_authorized',
      v_inserted = 1,
      NULL,
      CASE WHEN v_inserted = 1 THEN 'inserted_ok' ELSE 'unexpected_count' END
    );
  EXCEPTION
    WHEN OTHERS THEN
      GET STACKED DIAGNOSTICS v_sqlstate = RETURNED_SQLSTATE;
      INSERT INTO test_results VALUES (
        'manager_authorized', false, v_sqlstate, 'unexpected sqlstate'
      );
  END;

  -- Remainder of payload / tenant tests run as owner.
  PERFORM set_config('request.jwt.claim.sub', v_owner::text, true);
  PERFORM set_config(
    'request.jwt.claims',
    json_build_object('sub', v_owner::text, 'role', 'authenticated')::text,
    true
  );

  -- company_id_null
  BEGIN
    PERFORM public.import_customers(
      NULL,
      jsonb_build_array(jsonb_build_object('source_row', 2, 'name', 'step10a-x'))
    );
    INSERT INTO test_results VALUES (
      'company_id_null', false, NULL, 'expected SQLSTATE 22023'
    );
  EXCEPTION
    WHEN SQLSTATE '22023' THEN
      INSERT INTO test_results VALUES ('company_id_null', true, '22023', 'rejected');
    WHEN OTHERS THEN
      GET STACKED DIAGNOSTICS v_sqlstate = RETURNED_SQLSTATE;
      INSERT INTO test_results VALUES (
        'company_id_null', false, v_sqlstate, 'unexpected sqlstate'
      );
  END;

  -- payload_null
  BEGIN
    PERFORM public.import_customers(v_company_a, NULL);
    INSERT INTO test_results VALUES (
      'payload_null', false, NULL, 'expected SQLSTATE 22023'
    );
  EXCEPTION
    WHEN SQLSTATE '22023' THEN
      INSERT INTO test_results VALUES ('payload_null', true, '22023', 'rejected');
    WHEN OTHERS THEN
      GET STACKED DIAGNOSTICS v_sqlstate = RETURNED_SQLSTATE;
      INSERT INTO test_results VALUES (
        'payload_null', false, v_sqlstate, 'unexpected sqlstate'
      );
  END;

  -- payload_not_array
  BEGIN
    PERFORM public.import_customers(v_company_a, jsonb_build_object('x', 1));
    INSERT INTO test_results VALUES (
      'payload_not_array', false, NULL, 'expected SQLSTATE 22023'
    );
  EXCEPTION
    WHEN SQLSTATE '22023' THEN
      INSERT INTO test_results VALUES ('payload_not_array', true, '22023', 'rejected');
    WHEN OTHERS THEN
      GET STACKED DIAGNOSTICS v_sqlstate = RETURNED_SQLSTATE;
      INSERT INTO test_results VALUES (
        'payload_not_array', false, v_sqlstate, 'unexpected sqlstate'
      );
  END;

  -- empty_array
  BEGIN
    PERFORM public.import_customers(v_company_a, '[]'::jsonb);
    INSERT INTO test_results VALUES (
      'empty_array', false, NULL, 'expected SQLSTATE 22023'
    );
  EXCEPTION
    WHEN SQLSTATE '22023' THEN
      INSERT INTO test_results VALUES ('empty_array', true, '22023', 'rejected');
    WHEN OTHERS THEN
      GET STACKED DIAGNOSTICS v_sqlstate = RETURNED_SQLSTATE;
      INSERT INTO test_results VALUES (
        'empty_array', false, v_sqlstate, 'unexpected sqlstate'
      );
  END;

  -- more_than_500
  BEGIN
    PERFORM public.import_customers(
      v_company_a,
      (
        SELECT jsonb_agg(
          jsonb_build_object('source_row', g + 1, 'name', 'step10a-n' || g)
        )
        FROM generate_series(1, 501) g
      )
    );
    INSERT INTO test_results VALUES (
      'more_than_500', false, NULL, 'expected SQLSTATE 22023'
    );
  EXCEPTION
    WHEN SQLSTATE '22023' THEN
      INSERT INTO test_results VALUES ('more_than_500', true, '22023', 'rejected');
    WHEN OTHERS THEN
      GET STACKED DIAGNOSTICS v_sqlstate = RETURNED_SQLSTATE;
      INSERT INTO test_results VALUES (
        'more_than_500', false, v_sqlstate, 'unexpected sqlstate'
      );
  END;

  -- element_not_object
  BEGIN
    PERFORM public.import_customers(v_company_a, jsonb_build_array(1));
    INSERT INTO test_results VALUES (
      'element_not_object', false, NULL, 'expected SQLSTATE 22023'
    );
  EXCEPTION
    WHEN SQLSTATE '22023' THEN
      INSERT INTO test_results VALUES ('element_not_object', true, '22023', 'rejected');
    WHEN OTHERS THEN
      GET STACKED DIAGNOSTICS v_sqlstate = RETURNED_SQLSTATE;
      INSERT INTO test_results VALUES (
        'element_not_object', false, v_sqlstate, 'unexpected sqlstate'
      );
  END;

  -- unknown_key
  BEGIN
    PERFORM public.import_customers(
      v_company_a,
      jsonb_build_array(
        jsonb_build_object('source_row', 2, 'name', 'step10a-x', 'vat', '1')
      )
    );
    INSERT INTO test_results VALUES (
      'unknown_key', false, NULL, 'expected SQLSTATE 22023'
    );
  EXCEPTION
    WHEN SQLSTATE '22023' THEN
      INSERT INTO test_results VALUES ('unknown_key', true, '22023', 'rejected');
    WHEN OTHERS THEN
      GET STACKED DIAGNOSTICS v_sqlstate = RETURNED_SQLSTATE;
      INSERT INTO test_results VALUES (
        'unknown_key', false, v_sqlstate, 'unexpected sqlstate'
      );
  END;

  -- company_id_in_payload
  BEGIN
    PERFORM public.import_customers(
      v_company_a,
      jsonb_build_array(
        jsonb_build_object(
          'source_row', 2,
          'name', 'step10a-x',
          'company_id', v_company_b
        )
      )
    );
    INSERT INTO test_results VALUES (
      'company_id_in_payload', false, NULL, 'expected SQLSTATE 22023'
    );
  EXCEPTION
    WHEN SQLSTATE '22023' THEN
      INSERT INTO test_results VALUES (
        'company_id_in_payload', true, '22023', 'rejected'
      );
    WHEN OTHERS THEN
      GET STACKED DIAGNOSTICS v_sqlstate = RETURNED_SQLSTATE;
      INSERT INTO test_results VALUES (
        'company_id_in_payload', false, v_sqlstate, 'unexpected sqlstate'
      );
  END;

  -- source_row_missing
  BEGIN
    PERFORM public.import_customers(
      v_company_a,
      jsonb_build_array(jsonb_build_object('name', 'step10a-x'))
    );
    INSERT INTO test_results VALUES (
      'source_row_missing', false, NULL, 'expected SQLSTATE 22023'
    );
  EXCEPTION
    WHEN SQLSTATE '22023' THEN
      INSERT INTO test_results VALUES ('source_row_missing', true, '22023', 'rejected');
    WHEN OTHERS THEN
      GET STACKED DIAGNOSTICS v_sqlstate = RETURNED_SQLSTATE;
      INSERT INTO test_results VALUES (
        'source_row_missing', false, v_sqlstate, 'unexpected sqlstate'
      );
  END;

  -- source_row_string
  BEGIN
    v_elem := jsonb_build_object('source_row', '2', 'name', 'step10a-x');
    PERFORM public.import_customers(v_company_a, jsonb_build_array(v_elem));
    INSERT INTO test_results VALUES (
      'source_row_string', false, NULL, 'expected SQLSTATE 22023'
    );
  EXCEPTION
    WHEN SQLSTATE '22023' THEN
      INSERT INTO test_results VALUES ('source_row_string', true, '22023', 'rejected');
    WHEN OTHERS THEN
      GET STACKED DIAGNOSTICS v_sqlstate = RETURNED_SQLSTATE;
      INSERT INTO test_results VALUES (
        'source_row_string', false, v_sqlstate, 'unexpected sqlstate'
      );
  END;

  -- source_row_decimal (2.7 must not truncate)
  BEGIN
    PERFORM public.import_customers(
      v_company_a,
      jsonb_build_array(
        jsonb_build_object('source_row', 2.7, 'name', 'step10a-x')
      )
    );
    INSERT INTO test_results VALUES (
      'source_row_decimal', false, NULL, 'expected SQLSTATE 22023'
    );
  EXCEPTION
    WHEN SQLSTATE '22023' THEN
      INSERT INTO test_results VALUES ('source_row_decimal', true, '22023', 'rejected');
    WHEN OTHERS THEN
      GET STACKED DIAGNOSTICS v_sqlstate = RETURNED_SQLSTATE;
      INSERT INTO test_results VALUES (
        'source_row_decimal', false, v_sqlstate, 'unexpected sqlstate'
      );
  END;

  -- source_row_zero
  BEGIN
    PERFORM public.import_customers(
      v_company_a,
      jsonb_build_array(jsonb_build_object('source_row', 0, 'name', 'step10a-x'))
    );
    INSERT INTO test_results VALUES (
      'source_row_zero', false, NULL, 'expected SQLSTATE 22023'
    );
  EXCEPTION
    WHEN SQLSTATE '22023' THEN
      INSERT INTO test_results VALUES ('source_row_zero', true, '22023', 'rejected');
    WHEN OTHERS THEN
      GET STACKED DIAGNOSTICS v_sqlstate = RETURNED_SQLSTATE;
      INSERT INTO test_results VALUES (
        'source_row_zero', false, v_sqlstate, 'unexpected sqlstate'
      );
  END;

  -- source_row_negative
  BEGIN
    PERFORM public.import_customers(
      v_company_a,
      jsonb_build_array(jsonb_build_object('source_row', -1, 'name', 'step10a-x'))
    );
    INSERT INTO test_results VALUES (
      'source_row_negative', false, NULL, 'expected SQLSTATE 22023'
    );
  EXCEPTION
    WHEN SQLSTATE '22023' THEN
      INSERT INTO test_results VALUES ('source_row_negative', true, '22023', 'rejected');
    WHEN OTHERS THEN
      GET STACKED DIAGNOSTICS v_sqlstate = RETURNED_SQLSTATE;
      INSERT INTO test_results VALUES (
        'source_row_negative', false, v_sqlstate, 'unexpected sqlstate'
      );
  END;

  -- source_row_duplicate
  BEGIN
    PERFORM public.import_customers(
      v_company_a,
      jsonb_build_array(
        jsonb_build_object('source_row', 2, 'name', 'step10a-a'),
        jsonb_build_object('source_row', 2, 'name', 'step10a-b')
      )
    );
    INSERT INTO test_results VALUES (
      'source_row_duplicate', false, NULL, 'expected SQLSTATE 22023'
    );
  EXCEPTION
    WHEN SQLSTATE '22023' THEN
      INSERT INTO test_results VALUES (
        'source_row_duplicate', true, '22023', 'rejected'
      );
    WHEN OTHERS THEN
      GET STACKED DIAGNOSTICS v_sqlstate = RETURNED_SQLSTATE;
      INSERT INTO test_results VALUES (
        'source_row_duplicate', false, v_sqlstate, 'unexpected sqlstate'
      );
  END;

  -- name_missing
  BEGIN
    PERFORM public.import_customers(
      v_company_a,
      jsonb_build_array(jsonb_build_object('source_row', 2))
    );
    INSERT INTO test_results VALUES (
      'name_missing', false, NULL, 'expected SQLSTATE 22023'
    );
  EXCEPTION
    WHEN SQLSTATE '22023' THEN
      INSERT INTO test_results VALUES ('name_missing', true, '22023', 'rejected');
    WHEN OTHERS THEN
      GET STACKED DIAGNOSTICS v_sqlstate = RETURNED_SQLSTATE;
      INSERT INTO test_results VALUES (
        'name_missing', false, v_sqlstate, 'unexpected sqlstate'
      );
  END;

  -- name_blank
  BEGIN
    PERFORM public.import_customers(
      v_company_a,
      jsonb_build_array(jsonb_build_object('source_row', 2, 'name', '   '))
    );
    INSERT INTO test_results VALUES (
      'name_blank', false, NULL, 'expected SQLSTATE 22023'
    );
  EXCEPTION
    WHEN SQLSTATE '22023' THEN
      INSERT INTO test_results VALUES ('name_blank', true, '22023', 'rejected');
    WHEN OTHERS THEN
      GET STACKED DIAGNOSTICS v_sqlstate = RETURNED_SQLSTATE;
      INSERT INTO test_results VALUES (
        'name_blank', false, v_sqlstate, 'unexpected sqlstate'
      );
  END;

  -- email_wrong_type
  BEGIN
    PERFORM public.import_customers(
      v_company_a,
      jsonb_build_array(
        jsonb_build_object('source_row', 2, 'name', 'step10a-x', 'email', 1)
      )
    );
    INSERT INTO test_results VALUES (
      'email_wrong_type', false, NULL, 'expected SQLSTATE 22023'
    );
  EXCEPTION
    WHEN SQLSTATE '22023' THEN
      INSERT INTO test_results VALUES ('email_wrong_type', true, '22023', 'rejected');
    WHEN OTHERS THEN
      GET STACKED DIAGNOSTICS v_sqlstate = RETURNED_SQLSTATE;
      INSERT INTO test_results VALUES (
        'email_wrong_type', false, v_sqlstate, 'unexpected sqlstate'
      );
  END;

  -- phone_wrong_type
  BEGIN
    PERFORM public.import_customers(
      v_company_a,
      jsonb_build_array(
        jsonb_build_object('source_row', 2, 'name', 'step10a-x', 'phone', true)
      )
    );
    INSERT INTO test_results VALUES (
      'phone_wrong_type', false, NULL, 'expected SQLSTATE 22023'
    );
  EXCEPTION
    WHEN SQLSTATE '22023' THEN
      INSERT INTO test_results VALUES ('phone_wrong_type', true, '22023', 'rejected');
    WHEN OTHERS THEN
      GET STACKED DIAGNOSTICS v_sqlstate = RETURNED_SQLSTATE;
      INSERT INTO test_results VALUES (
        'phone_wrong_type', false, v_sqlstate, 'unexpected sqlstate'
      );
  END;

  -- notes_wrong_type
  BEGIN
    PERFORM public.import_customers(
      v_company_a,
      '[{"source_row":2,"name":"step10a-x","notes":[]}]'::jsonb
    );
    INSERT INTO test_results VALUES (
      'notes_wrong_type', false, NULL, 'expected SQLSTATE 22023'
    );
  EXCEPTION
    WHEN SQLSTATE '22023' THEN
      INSERT INTO test_results VALUES ('notes_wrong_type', true, '22023', 'rejected');
    WHEN OTHERS THEN
      GET STACKED DIAGNOSTICS v_sqlstate = RETURNED_SQLSTATE;
      INSERT INTO test_results VALUES (
        'notes_wrong_type', false, v_sqlstate, 'unexpected sqlstate'
      );
  END;

  -- length_limits
  BEGIN
    PERFORM public.import_customers(
      v_company_a,
      jsonb_build_array(
        jsonb_build_object('source_row', 2, 'name', repeat('n', 201))
      )
    );
    INSERT INTO test_results VALUES (
      'length_limits', false, NULL, 'expected SQLSTATE 22023'
    );
  EXCEPTION
    WHEN SQLSTATE '22023' THEN
      INSERT INTO test_results VALUES ('length_limits', true, '22023', 'rejected');
    WHEN OTHERS THEN
      GET STACKED DIAGNOSTICS v_sqlstate = RETURNED_SQLSTATE;
      INSERT INTO test_results VALUES (
        'length_limits', false, v_sqlstate, 'unexpected sqlstate'
      );
  END;

  -- atomic_failure: valid + invalid → no partial insert
  SELECT count(*) INTO v_count_before
  FROM public.clients
  WHERE company_id = v_company_a;

  BEGIN
    PERFORM public.import_customers(
      v_company_a,
      jsonb_build_array(
        jsonb_build_object('source_row', 2, 'name', 'step10a-atomic-ok'),
        jsonb_build_object('source_row', 3, 'name', '')
      )
    );
    INSERT INTO test_results VALUES (
      'atomic_failure', false, NULL, 'expected SQLSTATE 22023'
    );
  EXCEPTION
    WHEN SQLSTATE '22023' THEN
      SELECT count(*) INTO v_count_after
      FROM public.clients
      WHERE company_id = v_company_a;
      INSERT INTO test_results VALUES (
        'atomic_failure',
        v_count_after = v_count_before,
        '22023',
        CASE
          WHEN v_count_after = v_count_before THEN 'no_partial_insert'
          ELSE 'partial_insert_detected'
        END
      );
    WHEN OTHERS THEN
      GET STACKED DIAGNOSTICS v_sqlstate = RETURNED_SQLSTATE;
      INSERT INTO test_results VALUES (
        'atomic_failure', false, v_sqlstate, 'unexpected sqlstate'
      );
  END;

  -- company_id_from_param + email_other_tenant_ok + tenant_isolation
  -- best effort dello Step 10A for email dedupe across tenants
  BEGIN
    PERFORM set_config('request.jwt.claim.sub', v_owner::text, true);
    SELECT inserted_count INTO v_inserted
    FROM public.import_customers(
      v_company_b,
      jsonb_build_array(
        jsonb_build_object(
          'source_row', 2,
          'name', 'step10a-b-only',
          'email', 'shared.' || v_run_marker || '@example.invalid'
        )
      )
    );

    SELECT inserted_count, skipped_duplicate_count INTO v_inserted, v_skipped
    FROM public.import_customers(
      v_company_a,
      jsonb_build_array(
        jsonb_build_object(
          'source_row', 2,
          'name', 'step10a-a-shared',
          'email', 'shared.' || v_run_marker || '@example.invalid'
        )
      )
    );

    v_ok :=
      v_inserted = 1
      AND v_skipped = 0
      AND NOT EXISTS (
        SELECT 1
        FROM public.clients c
        WHERE c.company_id = v_company_a
          AND c.name = 'step10a-b-only'
      )
      AND EXISTS (
        SELECT 1
        FROM public.clients c
        WHERE c.company_id = v_company_a
          AND c.name = 'step10a-a-shared'
      )
      AND EXISTS (
        SELECT 1
        FROM public.clients c
        WHERE c.company_id = v_company_b
          AND c.name = 'step10a-b-only'
      );

    INSERT INTO test_results VALUES (
      'company_id_from_param',
      v_ok,
      NULL,
      CASE WHEN v_ok THEN 'param_company_id_only' ELSE 'tenant_mismatch' END
    );
    INSERT INTO test_results VALUES (
      'email_other_tenant_ok',
      v_ok,
      NULL,
      CASE WHEN v_ok THEN 'cross_tenant_email_ok' ELSE 'blocked_or_leak' END
    );
    INSERT INTO test_results VALUES (
      'tenant_isolation',
      v_ok,
      NULL,
      CASE WHEN v_ok THEN 'no_cross_tenant_rows' ELSE 'isolation_failed' END
    );
  EXCEPTION
    WHEN OTHERS THEN
      GET STACKED DIAGNOSTICS v_sqlstate = RETURNED_SQLSTATE;
      INSERT INTO test_results VALUES (
        'company_id_from_param', false, v_sqlstate, 'unexpected sqlstate'
      );
      INSERT INTO test_results VALUES (
        'email_other_tenant_ok', false, v_sqlstate, 'unexpected sqlstate'
      );
      INSERT INTO test_results VALUES (
        'tenant_isolation', false, v_sqlstate, 'unexpected sqlstate'
      );
  END;

  -- duplicate_email_payload (best effort dello Step 10A)
  BEGIN
    SELECT inserted_count, skipped_duplicate_count, skipped_source_rows
      INTO v_inserted, v_skipped, v_rows
    FROM public.import_customers(
      v_company_a,
      jsonb_build_array(
        jsonb_build_object(
          'source_row', 2,
          'name', 'step10a-dup-first',
          'email', 'dup.' || v_run_marker || '@example.invalid'
        ),
        jsonb_build_object(
          'source_row', 3,
          'name', 'step10a-dup-second',
          'email', 'dup.' || v_run_marker || '@example.invalid'
        )
      )
    );
    v_ok := v_inserted = 1 AND v_skipped = 1 AND v_rows = ARRAY[3];
    INSERT INTO test_results VALUES (
      'duplicate_email_payload',
      v_ok,
      NULL,
      CASE WHEN v_ok THEN 'best_effort_first_kept' ELSE 'dedupe_mismatch' END
    );
  EXCEPTION
    WHEN OTHERS THEN
      GET STACKED DIAGNOSTICS v_sqlstate = RETURNED_SQLSTATE;
      INSERT INTO test_results VALUES (
        'duplicate_email_payload', false, v_sqlstate, 'unexpected sqlstate'
      );
  END;

  -- duplicate_email_tenant (best effort dello Step 10A)
  BEGIN
    SELECT inserted_count, skipped_duplicate_count, skipped_source_rows
      INTO v_inserted, v_skipped, v_rows
    FROM public.import_customers(
      v_company_a,
      jsonb_build_array(
        jsonb_build_object(
          'source_row', 2,
          'name', 'step10a-dup-again',
          'email', 'dup.' || v_run_marker || '@example.invalid'
        )
      )
    );
    v_ok := v_inserted = 0 AND v_skipped = 1 AND v_rows = ARRAY[2];
    INSERT INTO test_results VALUES (
      'duplicate_email_tenant',
      v_ok,
      NULL,
      CASE WHEN v_ok THEN 'best_effort_tenant_skip' ELSE 'dedupe_mismatch' END
    );
  EXCEPTION
    WHEN OTHERS THEN
      GET STACKED DIAGNOSTICS v_sqlstate = RETURNED_SQLSTATE;
      INSERT INTO test_results VALUES (
        'duplicate_email_tenant', false, v_sqlstate, 'unexpected sqlstate'
      );
  END;

  -- rows_without_email
  BEGIN
    SELECT inserted_count INTO v_inserted
    FROM public.import_customers(
      v_company_a,
      jsonb_build_array(
        jsonb_build_object('source_row', 2, 'name', 'step10a-nomail-1'),
        jsonb_build_object('source_row', 3, 'name', 'step10a-nomail-2')
      )
    );
    INSERT INTO test_results VALUES (
      'rows_without_email',
      v_inserted = 2,
      NULL,
      CASE WHEN v_inserted = 2 THEN 'imported_ok' ELSE 'unexpected_count' END
    );
  EXCEPTION
    WHEN OTHERS THEN
      GET STACKED DIAGNOSTICS v_sqlstate = RETURNED_SQLSTATE;
      INSERT INTO test_results VALUES (
        'rows_without_email', false, v_sqlstate, 'unexpected sqlstate'
      );
  END;

  -- counts_coherent + result_no_pii + skipped_source_rows integers only
  BEGIN
    SELECT inserted_count, skipped_duplicate_count, skipped_source_rows
      INTO v_inserted, v_skipped, v_rows
    FROM public.import_customers(
      v_company_a,
      jsonb_build_array(
        jsonb_build_object(
          'source_row', 2,
          'name', 'step10a-count',
          'email', 'count.' || v_run_marker || '@example.invalid'
        )
      )
    );
    v_ok :=
      v_inserted = 1
      AND v_skipped = 0
      AND cardinality(v_rows) = 0
      AND NOT (to_jsonb(v_rows)::text ~* '@');
    INSERT INTO test_results VALUES (
      'counts_coherent',
      v_inserted = 1 AND v_skipped = 0,
      NULL,
      CASE
        WHEN v_inserted = 1 AND v_skipped = 0 THEN 'counts_ok'
        ELSE 'counts_mismatch'
      END
    );
    INSERT INTO test_results VALUES (
      'skipped_source_rows_integers',
      true,
      NULL,
      'integer_array_type_ok'
    );
    INSERT INTO test_results VALUES (
      'result_no_pii',
      v_ok,
      NULL,
      CASE WHEN v_ok THEN 'result_counts_only' ELSE 'pii_suspected' END
    );
  EXCEPTION
    WHEN OTHERS THEN
      GET STACKED DIAGNOSTICS v_sqlstate = RETURNED_SQLSTATE;
      INSERT INTO test_results VALUES (
        'counts_coherent', false, v_sqlstate, 'unexpected sqlstate'
      );
      INSERT INTO test_results VALUES (
        'skipped_source_rows_integers', false, v_sqlstate, 'unexpected sqlstate'
      );
      INSERT INTO test_results VALUES (
        'result_no_pii', false, v_sqlstate, 'unexpected sqlstate'
      );
  END;

  -- In-transaction residue counts for seed UUIDs only (no UUID printed).
  INSERT INTO test_results
  SELECT
    'residue_in_txn_' || s.kind,
    CASE s.kind
      WHEN 'user' THEN (
        SELECT count(*) FROM auth.users u WHERE u.id = s.id
      ) = 1
      WHEN 'company' THEN (
        SELECT count(*) FROM public.companies c WHERE c.id = s.id
      ) = 1
    END,
    NULL,
    'seed_row_present_before_rollback'
  FROM test_seed s
  WHERE s.kind IN ('user', 'company');

  INSERT INTO test_results
  SELECT
    'residue_in_txn_membership',
    count(*) = 5,
    NULL,
    'five_temp_memberships'
  FROM public.company_members m
  WHERE m.company_id IN (SELECT id FROM test_seed WHERE kind = 'company')
    AND m.user_id IN (SELECT id FROM test_seed WHERE kind = 'user');

  INSERT INTO test_results
  SELECT
    'residue_in_txn_clients',
    count(*) > 0,
    NULL,
    'temp_clients_present_before_rollback'
  FROM public.clients c
  WHERE c.company_id IN (SELECT id FROM test_seed WHERE kind = 'company');

END;
$body$;

SELECT test_name, passed, error_code, safe_message
FROM test_results
ORDER BY test_name;

SELECT
  COUNT(*) FILTER (WHERE passed) AS passed,
  COUNT(*) FILTER (WHERE NOT passed) AS failed,
  COUNT(*) AS total
FROM test_results;

-- run_marker for second-connection residue checks (also in test_results).
SELECT safe_message AS run_marker
FROM test_results
WHERE test_name = 'run_marker';

ROLLBACK;
